const express = require('express')
const jwt = require('jsonwebtoken')
const router = express.Router()
const SECRET = process.env.JWT_SECRET || 'realnest-development-secret'

function optionalUser(req, res, next) { const token = req.headers.authorization?.replace('Bearer ', ''); if (token) { try { req.user = jwt.verify(token, SECRET) } catch {} } next() }
function requireUser(req, res, next) { optionalUser(req, res, () => req.user ? next() : res.status(401).json({ message: 'Please sign in to manage properties.' })) }
function normalize(input, current = {}) {
  const status = input.status === 'For Rent' || input.status === 'rent' ? 'rent' : 'sale'
  return { ...current, title: String(input.title || current.title || '').trim(), type: String(input.type || current.type || 'Apartment'), status, location: String(input.location || current.location || '').trim(), city: String(input.city || current.city || input.location || current.city || '').trim(), price: Number(input.price ?? current.price), bedrooms: Number(input.bedrooms ?? current.bedrooms ?? 0), bathrooms: Number(input.bathrooms ?? current.bathrooms ?? 0), area: Number(input.area ?? current.area ?? 0), description: String(input.description || current.description || '').trim(), amenities: Array.isArray(input.amenities) ? input.amenities : (current.amenities || []), image_url: String(input.image_url || input.image || current.image_url || '').trim() || 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=85&auto=format&fit=crop', agent: String(input.agent || input.agentName || current.agent || 'RealNest Agent').trim(), agentPhone: String(input.agentPhone || current.agentPhone || '').trim(), agentEmail: String(input.agentEmail || current.agentEmail || '').trim() }
}
function validate(p) { if (!p.title || p.title.length < 6) return 'Title must be at least 6 characters.'; if (!p.location || !p.city) return 'Location and city are required.'; if (!Number.isFinite(p.price) || p.price <= 0) return 'Price must be greater than zero.'; if (!p.description || p.description.split(/\s+/).length < 8) return 'Description must contain at least 8 words.'; return null }

module.exports = ({ loadStore, saveStore }) => {
  const requireAgent = (req, res, next) => requireUser(req, res, () => loadStore().users.some(user => user.id === req.user.userId && user.role === 'agent') ? next() : res.status(403).json({ message: 'Only agent accounts can list or manage properties.' }))
  router.get('/', (req, res) => { const store = loadStore(); const { search, type, status, city } = req.query; let items = store.properties.filter(p => p.approval_status === 'approved'); if (search) { const q = search.toLowerCase(); items = items.filter(p => `${p.title} ${p.location} ${p.description}`.toLowerCase().includes(q)) }; if (type && type !== 'All') items = items.filter(p => p.type.toLowerCase() === String(type).toLowerCase()); if (status && status !== 'All') items = items.filter(p => p.status === String(status).toLowerCase().replace('for ', '')); if (city && city !== 'All Cities') items = items.filter(p => p.city === city); res.json(items) })
  router.get('/:id', (req, res) => { const item = loadStore().properties.find(p => p.id === Number(req.params.id) && p.approval_status === 'approved'); item ? res.json(item) : res.status(404).json({ message: 'Property not found.' }) })
  router.post('/', requireAgent, (req, res) => { const p = normalize(req.body); const error = validate(p); if (error) return res.status(400).json({ message: error }); const store = loadStore(); const item = { ...p, id: Date.now(), owner_id: req.user.userId, approval_status: 'pending', rejection_reason: '', created_at: new Date().toISOString(), rating: 0, reviews: 0 }; store.properties.unshift(item); saveStore(store); res.status(201).json({ ...item, message: 'Listing submitted for admin approval.' }) })
  router.put('/:id', requireAgent, (req, res) => { const store = loadStore(); const index = store.properties.findIndex(p => p.id === Number(req.params.id)); if (index < 0) return res.status(404).json({ message: 'Property not found.' }); const item = normalize(req.body, store.properties[index]); const error = validate(item); if (error) return res.status(400).json({ message: error }); store.properties[index] = item; saveStore(store); res.json(item) })
  router.delete('/:id', requireAgent, (req, res) => { const store = loadStore(); const before = store.properties.length; store.properties = store.properties.filter(p => p.id !== Number(req.params.id)); if (store.properties.length === before) return res.status(404).json({ message: 'Property not found.' }); saveStore(store); res.json({ message: 'Property deleted.' }) })
  return router
}
